// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_player_deaths = "CgkI77rysJYNEAIQAg"; // <GPGSID>
        public const string achievement_test = "CgkI77rysJYNEAIQAw"; // <GPGSID>
        public const string achievement_open_the_game_for_the_first_time = "CgkI77rysJYNEAIQAQ"; // <GPGSID>
        public const string achievement_test2 = "CgkI77rysJYNEAIQBA"; // <GPGSID>
        public const string achievement_test3 = "CgkI77rysJYNEAIQBQ"; // <GPGSID>
        public const string achievement_test4 = "CgkI77rysJYNEAIQBg"; // <GPGSID>

}

